baseurl = "http://southern-maine-aviation.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "Southern Maine Aviation"
theme = "creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Southern Maine Aviation"
	description = "Flight Training, Instruction and Services in Southern Maine FBO, Scenic Flights, Learn to Fly, Pilot Pathway, Sanford, Maine"

	# The path must be relative to the static folder
	favicon = "favicon_1.0.ico"


	# Navigation
	[params.navigation]
		brand = "<img src='../img/SMALogo.png'>"

	[params.navigation.links]
		news     = "News"
		services  = "Services"
		all_services  = "All Services"
		portfolio = "Portfolio"
		contact   = "Contact"

	[params.navigation.links.schedule]
			  title = "Schedule a Flight!"
			  link = "http://s09.myfbo.com/link.asp?fbo=paos"
			  icon = "fa-calendar"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		businessHours = "Open 7 days a week from 7 AM to 5 PM"
        altBusinessHours = "Open until 7 PM Memorial Day - Labor Day"
        phoneNumber = "207-324-8919"

	[[params.hero.list]]
		# To change the background of the hero section, replace the '1.jpg' at './static/img/hero' with your own.
		slogan     = "Learn To Fly Today!"
		subtitle   = "Whether you are a beginner or advanced, just starting out on your aviation journey or looking to enhance your skills we can work with you to create the perfect program. We have a wide range of planes and programs to give you the education experience you can't find anywhere else."
		buttonText = "Find Out More"
        buttonAction = "/fly"

	[[params.hero.list]]
		# To change the background of the hero section, replace the '2.jpg' at './static/img/hero' with your own.
		slogan     = "We're Here For You!"
		subtitle   = "We are a family oriented company providing services from small planes all the way to Airforce 1! We look forward to making your experience #1."
		buttonText = "Learn More About Us"
		buttonAction = "#news"

	[[params.hero.list]]
		# To change the background of the hero section, replace the '3.jpg' at './static/img/hero' with your own.
		slogan     = "Try a Scenic Flight!"
		subtitle   = "Scenic and Discovery Flights at Southern Maine Aviation are a truly memorable experience and a great introduction to flight. They also make great gifts!"
		buttonText = "Learn More Today"
		buttonAction = "/scenic-flights"

	[[params.hero.list]]
		# To change the background of the hero section, replace the '4.jpg' at './static/img/hero' with your own.
		slogan     = "Everything Aviation"
		subtitle   = "Southern Maine Aviation offers a full range of services, from beginner, advanced and custom tailored [flight training](/fly), [aircraft maintenance and storage](/aircraft-maintenance), and [corporate arrivals](/corporate-arrivals). We can exceed all your aviation needs."
		buttonText = "Find Out More"
		buttonAction = "#services"

	[params.news]
		headline = "News & Events"

	# News section
	[[params.news.list]]
		icon = "graduation-cap"
		headline    = "Fall Ground School Is Starting!"
		description = """Our Fall private pilot ground school is starting on Saturday September 8th and runs for ten weeks.
        The ground school is FAA Approved and covers all of the knowledge areas that you will need to pass the FAA
        Knowledge Test with flying colors! The classes are also a great way to refresh your memory and get back into
        flying if you have been on the ground too long. Many folks attend the ground school and fly on the same day. We
        have a great community of people attending these classes already. Please contact us with questions:

Andrew Button, Chief Instructor<br>
[480-721-7064](tel:480-721-7064)

<h3>Private Pilot Ground School</h3>

Saturdays 8:00-12:00 pm (September 8 - November 17th)

$325 (25% off for high school students)

We have great options available for books and supplies. Please inquire."""
		buttonText  = "Contact Us"
		buttonAction = "#contact"

	# News section
	[[params.news.list]]
		icon = "plane"
		headline    = "Southern Maine Aviation is Hiring Part Time Flight Instructors!"
		description = "Call [480-721-7064](tel:480-721-7064) to inquire"
		buttonText  = "Get started"
		buttonAction = "#contact"


	# Service section
	[params.services]
		headline = "At your service"
		description = "We offer a full range of services for General Aviation and corporate aircraft, plus an active flight training program. The FBO offers free computer usage and Wi-Fi, as well as a comfortable lounge and beverages for purchase."

		[[params.services.list]]
			icon = "fa-briefcase"
			title = "Corporate Arrivals"
			description = "We can make sure everything you need is here waiting upon your arrival."
			[params.services.list.link]
				 url = "/corporate-arrivals"
				 title = "Learn More"

        [[params.services.list]]
            icon = "fa-plane"
            title = "Learn To Fly"
            description = "There is so much more than we can fit here, so please give us a call or stop by."
            [params.services.list.link]
             	url = "/fly"
             	title = "Learn More"

        [[params.services.list]]
			icon = "fa-binoculars"
			title = "Scenic Flights"
			description = "Make great Gifts, and are memorable experiences."
			[params.services.list.link]
				 url = "/scenic-flights"
				 title = "Learn More"

		[[params.services.list]]
            icon = "fa-wrench"
            title = "Aircraft Maintenance"
            description = "Our award-winning mechanics can help give you the peace of mind that comes from knowing that your aircraft is in top notch condition and has been inspected thoroughly and professionally. "
			[params.services.list.link]
				 url = "/aircraft-maintenance"
				 title = "Learn More"


	 # Corporate Service section
	[params.corporate_services]
		headline = "Corporate Arrival Services"
		description = """After hours available on request, $75.00/hour.

Call <a href='tel:2073248919'>207-324-8919</a> during business hours.<br/>
Call <a href='tel:2076519308'>207-651-9308</a> after hours emergency for <span style='white-space:nowrap;'> Mark Damuth - General Manager</span>"""

		[[params.corporate_services.list]]
			icon = "fa-usd"
			title = "Fees"
			description = "Reasonable rates on aviation services."
			[params.corporate_services.list.link]
				 url = "#fees"
				 title = "Learn More"

	 	[[params.corporate_services.list]]
			icon = "fa-cutlery"
			title = "Dining"
			description = "Area dining options."
			[params.corporate_services.list.link]
				 url = "#restaurants"
				 title = "Learn More"

		[[params.corporate_services.list]]
			icon = "fa-tachometer"
			title = "Fuel"
			description = "High quality aviation grade fuel options."
			[params.corporate_services.list.link]
				 url = "#fuel"
				 title = "Learn More"

	 	[[params.corporate_services.list]]
			 icon = "fa-building"
			 title = "Lodging"
			 description = "Area lodging."
			 [params.corporate_services.list.link]
				url = "#lodging"
				title = "Learn More"

	 	[[params.corporate_services.list]]
			icon = "fa-car"
			title = "Transportation"
			description = "Getting around once you get here."
			[params.corporate_services.list.link]
				 url = "#ground-transportation"
				 title = "Learn More"

		[[params.corporate_services.list]]
			 icon = "fa-wrench"
			 title = "Maintenance"
			 description = "Our award-winning mechanics can help give you the peace of mind that comes from knowing that your aircraft is in top notch condition and has been inspected thoroughly and professionally. "
			[params.corporate_services.list.link]
				 url = "#maintenance"
				 title = "Learn More"



#    # Aside section
#	[params.aside]
#		headline = "Upcoming Events"
#    	description = """The next Drone class will be taught by Southern Maine Aviation Instructors at the Portland Campus of Southern Maine Community College!
#To register go to the SMCC website and go to the Continuing Studies section or use this link:
#
#[Register Here](//google.com)
#
#Look for this:
#Intro to sUAS - Drone 101
#(AVIA 800 01)
#
#
#4 nights
#03/13/18 - 03/22/18
#Tuesdays 5:30PM-8PM
#Thursdays 5:30PM-8PM
#
#
#The cost will be $225.00"""
#
#		[params.aside.button]
#			text = "Contact Us"
#			link = "mailto:fly@flyingsma.com"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start flying with us? That's great! Give us a call or send us an email and we will get back to you soon!"
		phone = "207-324-8919"
		email = "fly@flyingsma.com"
		facebook = "https://www.facebook.com/SouthernMaineAviation/"
		streetAddressLine1 = "199 Airport Road"
		streetAddressLine2 = "Sanford, Maine 04073"
		gmapsAddress = "Southern Maine Aviation, 199 Airport Rd, Sanford, ME 04073, USA"
		gmapsEmbedURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2898.8488587129677!2d-70.71279048432662!3d43.40108837671419!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cb2b440a2eb5a67%3A0xa3a092f530c9d102!2sSouthern+Maine+Aviation!5e0!3m2!1sen!2spe!4v1525538071837"

	# Footer
	[params.footer.copyright]
		name = "Southern Maine Aviation LLC"
		year = "2018"

	# Fly
	[params.fly]
		title = "Fly with Souther Maine Aviation"

	# Fleet
	[[params.fleet.list]]
		title = "C172SP G1000 N11682"
		description = """New to our fleet! 2006 Skyhawk G1000 glass panel is here!
IFR certified with KAP 140 auto pilot will make an easy transation from our other SPs.
For students seeking to become a professional pilot, the G1000 is the most widely used glass trainer platform.

<a href='/PDF/G1000 Checkout Policy sheet.pdf' target='_blank')>G1000 Checkout Policy</a>"""
		imageUrl = "N11682.jpg"
		pricing = "$160/hour"

	# Fleet
	[[params.fleet.list]]
		title = "Citabria 7GCBC N291CA"
		description = """Our 2004 Citabria 7GCBC is a great taildragger, with awesome responsiveness and visibility. It is available for solo rental, tailwheel instruction and spin training endorsements
  Garmin 250XL manual."""
		imageUrl = "N291CA_plane.jpg"
		pricing = "$135/hour"

	# Fleet
	[[params.fleet.list]]
		title = "C172 SP N53468"
		description = """Our 2003 Skyhawk SPs are the backbone of our training fleet. IFR certified with KAP140 autopilot, King KLN94 GPS, and 180hp."""
		imageUrl = "N53468.jpg"
		pricing = "$140/hour"

	# Fleet
	[[params.fleet.list]]
		title = "C172 SP N916BA"
		description = """Our 2002 Skyhawk SPs are the backbone of our training fleet. IFR certified with KAP140 autopilot, King KLN94 GPS, and 180hp."""
		imageUrl = "Skyhawk916BAExterior.jpg"
		pricing = "$140/hour"

	# Fleet
	[[params.fleet.list]]
		title = "C172 SP N172TG"
		description = """2002 Skyhawk SPs are the backbone of our training fleet. IFR certified with KAP140 autopilot, King KLN94 GPS, and 180hp. and JPI-701."""
		imageUrl = "N172TG.jpg"
		showImage = true
		pricing = "$140/hour"

	# Fleet
	[[params.fleet.list]]
		title = "C182 RG N7131S"
		description = """Wow -- HSI, DME, KAP/KFC 200 autopilot w/ flight director, traffic, King KLN94 GPS and 150 kt cruise! Retractable gear and 235hp."""
		imageUrl = "N7131S.jpg"
		pricing = "$175/hour"


  	# Fleet
	[[params.fleet.list]]
		title = "Redbird Motion Simulator"
		description = """Our FAA-approved advanced training device simulates a traditional Skyhawk as well as a G1000 Skyhawk."""
		imageUrl = "rbinterior.jpg"
		pricing = "$70/hour"


	[params.pilotPathway.form]
		email = "kevin@greenhopperdesign.com"
		message = """Great! We can help set up a program that will fit your interests perfectly! Submit the form below or contact us at <a href='tel:2073248919'>207-324-8919</a> and we'll start working with you to set up the perfect program today."""
		subject = "Pilot Pathway Interest"
		cc = "kevin@greenhopperdesign.com"
		icon = "plane"
		image = "pilot-pathway-4.jpg"

	[[params.pilotPathway.list]]
		step = 1
		icon = "plane"
		start = true
		question = "Why do you want to learn to fly?"
		image = "pilot-pathway-1.jpg"
		[[params.pilotPathway.list.answers.list]]
			nextStep = 2
			answerText = "Career opportunities"
		[[params.pilotPathway.list.answers.list]]
			nextStep = 2
			answerText = "Seems like a fun hobby"

	[[params.pilotPathway.list]]
		step = 2
		icon = "plane"
		question = "What sparked the interest?"
		image = "pilot-pathway-2.jpg"
		[[params.pilotPathway.list.answers.list]]
			nextStep = 3
			answerText = "I've always been interested in aviation"
		[[params.pilotPathway.list.answers.list]]
			nextStep = 3
			answerText = "Friends and family"

	[[params.pilotPathway.list]]
		step = 3
		icon = "plane"
		question = "Paved runways at \"point b\" or backcountry grass strips in more remote areas?"
		image = "pilot-pathway-3.jpg"
		[[params.pilotPathway.list.answers.list]]
			nextStep = "last"
			answerText = "Paved"
		[[params.pilotPathway.list.answers.list]]
			nextStep = "last"
			answerText = "Grass strips"

	[params.thanks]
		message = "Thank you! We will be in contact soon."
		[params.thanks.button]
			text = "Return to Home"
			url = "/"


	# Lodging
	[[params.lodging.list]]
		title = "Hampton Inn and Suites"
		address = """900 Post Road
Wells, Maine 04090"""
		phone = "207-646-0555"
		description = """10.2 miles from KSFM"""
		imageUrl = "Wells_Hampton_Inn.jpg"
		pricing = "call for seasonal pilot discounts"
		gmapsEmbedURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2903.660121788136!2d-70.59013548451374!3d43.30043887913499!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x7561240bc72bb6a5!2sHampton+Inn+%26+Suites+Wells-Ogunquit!5e0!3m2!1sen!2spe!4v1530108729724"

	# Lodging
	[[params.lodging.list]]
		title = "Holiday Inn Express Biddeford"
		address = """45 Barra Road
Biddeford, Maine 04005"""
		phone = "207-294-6464"
		description = """16 miles from KSFM"""
		imageUrl = "Biddeford_Holiday_Inn_Express.jpg"
		pricing = "call for pilot discounts"
		gmapsEmbedURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2894.88749237339!2d-70.49381454878161!3d43.48381827128233!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cb2a53cc8537ae9%3A0x93a45743b49d5b5d!2sHoliday+Inn+Express+Biddeford!5e0!3m2!1sen!2spe!4v1530111828730"

	# Lodging
	[[params.lodging.list]]
		title = "Hampton Inn Saco / Biddeford"
		address = """48 Industrail Park Road
Saco, Maine 04072"""
		phone = "207-282-7222"
		description = """20 miles from KSFM"""
		imageUrl = "Biddeford_Hampton_Inn.jpg"
		pricing = "call and mention Southern Maine Aviation for pilot discount program"
		gmapsEmbedURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2892.892697804521!2d-70.44839324878065!3d43.5254302685986!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cb2a36314549eb5%3A0xacf954d1696ec797!2sHampton+Inn+Saco%2FBiddeford!5e0!3m2!1sen!2spe!4v1530111962446"

	# Dining
	# Restaurants
	[[params.restaurants.list]]
		title = "Cockpit Cafe (on the field)"
		url = "https://www.facebook.com/pages/Cockpit-Cafe/150465441662943"

	# Restaurants
	[[params.restaurants.list]]
		title = "Shains of Maine"
		url = "http://www.shainsofmaine.com/"

	# Restaurants
	[[params.restaurants.list]]
		title = "Lords Clam Box"
		url = "http://lordsclambox.com/"

	# Catering
	[[params.catering.list]]
		title = "Jonathan's"
		phone = "207-646-4777"

	# Catering
	[[params.catering.list]]
		title = "Day Tripper Catering"
		phone = "603-380-6079"

	# Catering
	[[params.catering.list]]
		title = "CockPit Cafe"
		phone = "207-324-7332"
#		phone2 = "207-324-5717"



	# Ground Transport
	# rental cars
	[[params.rental_cars.list]]
		title = "Enterprise"
		phone = "207-324-8122"

	# rental cars
	[[params.rental_cars.list]]
		title = "Hertz"
		phone = "207-324-7368"

	# rental cars
	[[params.rental_cars.list]]
		title = "Avis"
		phone = "207-874-7501"

	# taxis
	[[params.taxis.list]]
		title = "Frontline Taxi"
		name = "William \"Bucky\" Collins owner operator"
		description = "7 passengar Dodge Caravans"
		phone = "207-490-1214"

	# taxis
	[[params.taxis.list]]
		title = "J&M Taxi"
		name = "Mark Bshara owner operator"
		description = "7 passengar Dodge Caravans"
		phone = "207-490-2222"


	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
