baseurl = "http://southern-maine-aviation.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "Southern Maine Aviation"
theme = "creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Southern Maine Aviation"
	description = "Flight Training, Instruction and Services in Southern Maine"

	# The path must be relative to the static folder
	favicon = "favicon_1.0.ico"


	# Navigation
	[params.navigation]
		brand = "<img src='../img/SMALogo.png'>"

	[params.navigation.links]
		about     = "About"
		services  = "Services"
		portfolio = "Portfolio"
		contact   = "Contact"

	[params.navigation.links.schedule]
			  title = "Schedule a Flight!"
			  link = "http://s09.myfbo.com/link.asp?fbo=paos"
			  icon = "fa-calendar"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		businessHours = "Open 7 days a week from 7 AM to 5 PM"
        altBusinessHours = "Open until 7 PM Memorial Day - Labor Day"
        phoneNumber = "207-324-8919"

	[[params.hero.list]]
		# To change the background of the hero section, replace the '1.jpg' at './static/img/hero' with your own.
		slogan     = "Learn To Fly Today!"
		subtitle   = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
		buttonText = "Find out more"
        buttonAction = "#contact"

	[[params.hero.list]]
		# To change the background of the hero section, replace the '2.jpg' at './static/img/hero' with your own.
		slogan     = "We're Here For You!"
		subtitle   = "We are a family oriented company providing services from small planes all the way to Airforce 1!"
		buttonText = "Learn More About Us"

	# About section
	[[params.about.list]]
		icon = "plane"
		headline    = "Southern Maine Aviation is Hiring Part Time Flight Instructors!"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Get started"


	# About section
	[[params.about.list]]
		icon = "book"
		headline    = "Lorem ipsum dolor sit amet"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Lorem ipsum"
		buttonAction = "#"

	# About section
	[[params.about.list]]
		icon = "graduation-cap"
		headline    = "Summer Ground School Is Starting!"
		description = """Our summer private pilot ground school is starting on Saturday June 9th and runs for ten weeks.
        The ground school is FAA Approved and covers all of the knowledge areas that you will need to pass the FAA
        Knowledge Test with flying colors! The classes are also a great way to refresh your memory and get back into
        flying if you have been on the ground too long. Many folks attend the ground school and fly on the same day. We
        have a great community of people attending these classes already. Please contact us with questions:

Andrew Button, Chief Instructor<br>
[480-721-7064](tel:480-721-7064)

<h2>Private Pilot Ground School</h2>

Saturdays 8:00-12:00 pm (June 9 - August 18th)

$325

We have great options available for books and supplies. Please inquire."""
		buttonText  = "Contact Us"
		buttonAction = "#contact"


#	# About section
#	[[params.about.list]]
#		icon = "facebook-square"
#		headline    = "Lorem ipsum dolor sit amet"
#		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
#		buttonText  = "Lorem ipsum"
#		buttonAction = "#"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-plane"
            title = "Learn To Fly"
            description = "There is so much more than we can fit here, so please give us a call or stop by."

        [[params.services.list]]
			icon = "fa-binoculars"
			title = "Scenic Flights"
			description = "Make great Gifts, and are memorable experiences."

		[[params.services.list]]
            icon = "fa-wrench"
            title = "Aircraft Maintenance"
            description = "Our award-winning mechanics can help give you the peace of mind that comes from knowing that your aircraft is in top notch condition and has been inspected thoroughly and professionally. "

        [[params.services.list]]
            icon = "fa-flag"
            title = "FBO"
            description = "Southern Maine Aviation is open 7 days a week from 7 am to 5pm, with extended evening hours until 7pm from Memorial Day through Labor Day and after hours available upon request."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Upcoming Events"
    description = """The next Drone class will be taught by Southern Maine Aviation Instructors at the Portland Campus of Southern Maine Community College!
To register go to the SMCC website and go to the Continuing Studies section or use this link:

[Register Here](//google.com)

Look for this:
Intro to sUAS - Drone 101
(AVIA 800 01)


4 nights
03/13/18 - 03/22/18
Tuesdays 5:30PM-8PM
Thursdays 5:30PM-8PM


The cost will be $225.00"""

		[params.aside.button]
			text = "Contact Us"
			link = "mailto:fly@flyingsma.com"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start flying with us? That's great! Give us a call or send us an email and we will get back to you soon!"
		phone = "207-324-8919"
		email = "fly@flyingsma.com"
		facebook = "https://www.facebook.com/SouthernMaineAviation/"
		streetAddressLine1 = "199 Airport Road"
		streetAddressLine2 = "Sanford, Maine 04073"
		gmapsAddress = "Southern Maine Aviation, 199 Airport Rd, Sanford, ME 04073, USA"
		gmapsEmbedURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2898.8488587129677!2d-70.71279048432662!3d43.40108837671419!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cb2b440a2eb5a67%3A0xa3a092f530c9d102!2sSouthern+Maine+Aviation!5e0!3m2!1sen!2spe!4v1525538071837"

	# Fo0ter
	[params.footer.copyright]
		name = "Southern Maine Aviation LLC"
		year = "2018"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
